name=WILLOW
version=1.0.0
author=Noah Ruimveld
maintainer=Noah Ruimveld <nruimveld@gmail.com>
sentence=Wrapped Interfaces for Low-level Locomotion and Odometry Workflows
paragraph=Modular Arduino motor-control library with swappable drivers, encoders, and speed or position controllers.
category=Device Control
url=https://github.com/nruimveld7/WILLOW
architectures=*
includes=WILLOW.h
